export const gallery=[{
    "id":1,
    "title": "Clay Shephard",
    "RenderEngine": "Blender Evee",
    "Date": "September 24, 2020",
    "img": "/images/AbinadiRender.png",
},
{
    "id":2,
    "title": "Angel Cemetary",
    "RenderEngine": "Blender Cycles",
    "Date": "March 19, 2022",
    "img": "/images/AngleCemetaryCoverArt.png",
},
{
    "id":3,
    "title": "Elysium",
    "RenderEngine": "Blender Cycles",
    "Date": "April 26, 2021",
    "img": "/images/asdf.png",
},
{
    "id":4,
    "title": "Cyborg Portrait",
    "RenderEngine": "Blender Cycles",
    "Date": "August 30, 2021",
    "img": "/images/BirdHelmLogo.png",
},
{
    "id":5,
    "title": "Crystal Cave",
    "RenderEngine": "Blender Cycles",
    "Date": "November 16, 2020",
    "img": "/images/Cave2.png",
},
{
    "id":6,
    "title": "Crystal Cave The Tree",
    "RenderEngine": "Blender Cycles",
    "Date": "November 28, 2020",
    "img": "/images/CaveWithTreeRender.png",
},
{
    "id":7,
    "title": "Cursed",
    "RenderEngine": "Blender Cycles",
    "Date": "October 2, 2020",
    "img": "/images/Curse1.png",
},
{
    "id":8,
    "title": "Echo Arena",
    "RenderEngine": "Blender Cycles",
    "Date": "May 26, 2021",
    "img": "/images/EchoArena.png",
},
{
    "id":9,
    "title": "Procedural Eyeballs",
    "RenderEngine": "Blender Cycles",
    "Date": "June 7, 2021",
    "img": "/images/EyeballsProcedural.png",
},
{
    "id":10,
    "title": "Fantasy Port",
    "RenderEngine": "Blender Cycles",
    "Date": "July 30, 2021",
    "img": "/images/FantasyIsolatedPort.png",
},{
    "id":11,
    "title": "Commissioned Portrait",
    "RenderEngine": "Blender Evee",
    "Date": "February 7, 2022",
    "img": "/images/GirlCommision.png",
},
{
    "id":12,
    "title": "Nothic Library",
    "RenderEngine": "Blender Cycles",
    "Date": "December 7, 2020",
    "img": "/images/NothicLibrary.png",
},
{
    "id":13,
    "title": "Monkey Island",
    "RenderEngine": "Blender Cycles",
    "Date": "February 17, 2022",
    "img": "/images/PinkIslandWithFocus.png",
},
{
    "id":14,
    "title": "Poison",
    "RenderEngine": "Blender Cycles",
    "Date": "October 3, 2020",
    "img": "/images/Poison1Day3.png",
},
{
    "id":15,
    "title": "My Fuzzy Friend",
    "RenderEngine": "Blender Cycles",
    "Date": "May 15, 2020",
    "img": "/images/received_847716175696025.png",
},
{
    "id":16,
    "title": "Unexplored Waters",
    "RenderEngine": "Blender Cycles",
    "Date": "May 25, 2021",
    "img": "/images/WateryCave.png",
},
{
    "id":17,
    "title": "Scifi Cowboy",
    "RenderEngine": "Blender Evee",
    "Date": "April 14, 2022",
    "img": "/images/ScifiCowBoyWIPEVEE.png",
},
{
    "id":18,
    "title": "Scifi Revolver Concept",
    "RenderEngine": "Blender Cycles",
    "Date": "April 13, 2022",
    "img": "/images/ScifiPistolConceptPurpleLights.png",
},
{
    "id":19,
    "title": "An Ocean of Space",
    "RenderEngine": "Blender Cycles",
    "Date": "February 20, 2022",
    "img": "/images/WaterSpace.png",
},
{
    "id":20,
    "title": "Space Dog",
    "RenderEngine": "Blender Evee",
    "Date": "May 3, 2021",
    "img": "/images/UFODogEvee.png",
},
{
    "id":21,
    "title": "Smoking Monkey",
    "RenderEngine": "Blender Cycles",
    "Date": "June 7, 2021",
    "img": "/images/WeedMonkey.png",
}



]